### ISSUE TITLE
Requirement tracker of the project.

### ISSUE THREAD

**Issue by pibebtol** [pibebtol/slr-toolkit#9]
#### Task:
Renew the graphing of the taxonomies in the SLR-Toolkit.

#### Requirements for finishing the project:

- [x] new charting with longer support
- [x] bar chart and bubble matrix chart
- [x] export of the graph as SVG
- [x] export of the taxonomy data as CSV
- [x] newer and fresher design
- [x] bubble labels for the bubble chart
- [x] legend for the bubble chart
- [x] color for the bubble chart
- [x] color bubble chart default to gray with black border
- [x] hint for incorrect amount of taxonomy values (tooltip/disable enable button?)
- [x] refactor (take out the original charting)
- [x] check for windows and make a release
- [x] create a pull request
- [ ] data concept?

**Comment by pibebtol** [comment]
- [ ] color for the bubble chart
- [ ] data concept?

**Comment by pibebtol** [comment]
folien als dokumentation -> technische und inhaltliche doku -> Verteidigung wäre dann nur eine kurze Demo, was gemacht wurde

**Comment by pibebtol** [comment]
Data Concept is not in the scope of that project.
